name: Build Svelte App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvmrc.outputs.node_version }}'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build